title: Mews Documentation
baseurl: /public

defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"

markdown: kramdown

kramdown:
  input: GFM
  toc_levels: 1..3
